# Generated by Django 4.2.9 on 2024-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobposition_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
