# Generated by Django 4.2.9 on 2024-05-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_profileuser_jobposition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrequest',
            name='jobdis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
