# Generated by Django 4.2.9 on 2024-05-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_alter_comrequest_jobdis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comrequest',
            name='comspec',
        ),
        migrations.AlterField(
            model_name='comrequest',
            name='comtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.computertype'),
        ),
    ]
