# Generated by Django 4.2.9 on 2024-09-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_remove_comrequest_comspec_alter_comrequest_comtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkexternal',
            old_name='url',
            new_name='linkurl',
        ),
    ]
