# Generated by Django 4.2.9 on 2024-09-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_rename_url_linkexternal_linkurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkexternal',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
