# Generated by Django 4.2.9 on 2024-09-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_linkexternal_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='msg',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
