# Generated by Django 4.2.9 on 2024-09-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_alter_ourservices_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrequest',
            name='jobdis',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
