# Generated by Django 4.2.9 on 2024-09-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0014_repairandpartchange_deviceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comnumber',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
