# Generated by Django 4.2.9 on 2024-09-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0015_alter_computeraccessory_comnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comnumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='repairandpartchange',
            name='deviceID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
