# Generated by Django 4.2.9 on 2024-09-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0018_repairandpartchange_partchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='comserailnumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
