# Generated by Django 4.2.9 on 2024-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0019_computeraccessory_comserailnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comphoto',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='comphoto'),
        ),
    ]
