# Generated by Django 4.2.9 on 2024-09-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0020_alter_computeraccessory_comphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comstatus',
            field=models.CharField(blank=True, choices=[('ใช้งาน', 'ใช้งาน'), ('ซ่อมบำรุง', 'ซ่อมบำรุง'), ('รอจำหน่าย', 'รอจำหน่าย'), ('จำหน่าย', 'จำหน่าย')], default='ใช้งาน', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repairandpartchange',
            name='repairstatus',
            field=models.CharField(blank=True, choices=[('ส่งซ่อม', 'ส่งซ่อม'), ('กำลังซ่อม', 'กำลังซ่อม'), ('ตรวจงานซ่อม', 'ตรวจงานซ่อม'), ('ส่งคืน', 'ส่งคืน')], default='ส่งซ๋อม', max_length=50, null=True),
        ),
    ]
