# Generated by Django 4.2.9 on 2024-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0023_remove_repairandpartchange_budget_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computeraccessory',
            old_name='comnumber',
            new_name='deviceID',
        ),
        migrations.AlterField(
            model_name='repairandpartchange',
            name='repairstatus',
            field=models.CharField(blank=True, choices=[('ส่งซ่อม', 'ส่งซ่อม'), ('กำลังซ่อม', 'กำลังซ่อม'), ('ส่งคืน', 'ส่งคืน')], default='ส่งซ่อม', max_length=50, null=True),
        ),
    ]
