# Generated by Django 4.2.9 on 2024-09-15 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0024_rename_comnumber_computeraccessory_deviceid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(blank=True, max_length=50, null=True)),
                ('deviceModel', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, max_length=100, null=True)),
                ('deviceBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.combranding')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.profileuser')),
            ],
        ),
    ]
