# Generated by Django 4.2.9 on 2024-09-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0025_borrowdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdevice',
            name='datefinish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowdevice',
            name='datestart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
