# Generated by Django 4.2.9 on 2024-09-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0026_borrowdevice_datefinish_borrowdevice_datestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdevice',
            name='deviceStatus',
            field=models.BooleanField(default=False),
        ),
    ]
