# Generated by Django 4.2.9 on 2024-09-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0027_borrowdevice_devicestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comstatus',
            field=models.CharField(blank=True, choices=[('ใช้งาน', 'ใช้งาน'), ('ยื่มใช้งาน', 'ยื่มใช้งาน'), ('ซ่อมบำรุง', 'ซ่อมบำรุง'), ('รอจำหน่าย', 'รอจำหน่าย'), ('จำหน่าย', 'จำหน่าย')], default='ใช้งาน', max_length=100, null=True),
        ),
    ]
