# Generated by Django 4.2.9 on 2024-09-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0028_alter_computeraccessory_comstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='comborrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computeraccessory',
            name='comstatus',
            field=models.CharField(blank=True, choices=[('ใช้งาน', 'ใช้งาน'), ('ซ่อมบำรุง', 'ซ่อมบำรุง'), ('รอจำหน่าย', 'รอจำหน่าย'), ('จำหน่าย', 'จำหน่าย')], default='ใช้งาน', max_length=100, null=True),
        ),
    ]
