# Generated by Django 4.2.9 on 2024-09-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0029_computeraccessory_comborrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comborrow',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
