# Generated by Django 4.2.9 on 2024-09-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0030_alter_computeraccessory_comborrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdevice',
            name='comtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.computertype'),
        ),
    ]
