# Generated by Django 4.2.9 on 2024-09-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0034_alter_repairandpartchange_repairstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comstatus',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.repairstatus'),
        ),
    ]
