# Generated by Django 4.2.9 on 2024-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0035_alter_computeraccessory_comstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='hddtype',
            field=models.TextField(blank=True, choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=500, null=True),
        ),
    ]
