# Generated by Django 4.2.9 on 2024-10-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0036_computeraccessory_hddtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdevice',
            name='returnBack',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='computeraccessory',
            name='hddtype',
            field=models.TextField(blank=True, choices=[('SSD', 'SSD'), ('HDD', 'HDD')], default='SSD', max_length=500, null=True),
        ),
    ]
