# Generated by Django 4.2.9 on 2024-10-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0037_borrowdevice_returnback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdevice',
            name='itemRecorder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
