# Generated by Django 4.2.9 on 2024-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0038_borrowdevice_itemrecorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
