# Generated by Django 4.2.9 on 2024-11-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0039_computeraccessory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='remark',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
