# Generated by Django 4.2.9 on 2024-11-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0040_computeraccessory_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='hddtype',
            field=models.TextField(blank=True, choices=[('ไม่มีฮาร์ดดิสก์', 'ไม่มีฮาร์ดดิสก์'), ('SSD', 'SSD'), ('HDD', 'HDD')], default='SSD', max_length=500, null=True),
        ),
    ]
