# Generated by Django 4.2.9 on 2024-11-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0041_alter_computeraccessory_hddtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='user_status',
            field=models.BooleanField(default=True),
        ),
    ]
