# Generated by Django 4.2.9 on 2024-11-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0042_profileuser_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='user_status',
            new_name='user_active',
        ),
    ]
