# Generated by Django 4.2.9 on 2024-12-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0043_rename_user_status_profileuser_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='user_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
