# Generated by Django 4.2.9 on 2024-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0044_alter_profileuser_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='usergroup',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('editer', 'editer'), ('reporter', 'reporter'), ('trainee', 'trainee')], max_length=100, null=True),
        ),
    ]
