# Generated by Django 4.2.9 on 2025-02-04 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0045_alter_profileuser_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='photo1au',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='photo1au'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='photo1ac',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='photo1ac'),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='trophy',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='trophy'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_doc',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='doctor'),
        ),
        migrations.AlterField(
            model_name='itwebblog',
            name='imagewebblog',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='ITWebBlog'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo1',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='photo1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo2',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='photo2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_photo',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='title_photo'),
        ),
        migrations.AlterField(
            model_name='onepage',
            name='file',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='onepage'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='image1',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='sevicephoto'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='image2',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='sevicephoto'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='image3',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='sevicephoto'),
        ),
        migrations.AlterField(
            model_name='photoheaderhomepage',
            name='photoheader',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='photoheader'),
        ),
        migrations.AlterField(
            model_name='programoffice',
            name='program_photo',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='programphoto'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='photosect',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='photosections'),
        ),
        migrations.CreateModel(
            name='PhotoComputerAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_photo', models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='hw_photo')),
                ('hw_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.computeraccessory')),
            ],
        ),
    ]
