# Generated by Django 4.2.9 on 2025-02-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0046_alter_aboutus_photo1au_alter_calltoaction_photo1ac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo2',
        ),
    ]
