# Generated by Django 4.2.9 on 2025-02-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0047_remove_news_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo1',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='news_photo1'),
        ),
    ]
