# Generated by Django 4.2.9 on 2025-02-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0048_alter_news_photo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo1',
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_photo', models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='news_photo1')),
                ('news_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.news')),
            ],
        ),
    ]
