# Generated by Django 4.2.9 on 2025-02-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0049_remove_news_photo1_newsphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programoffice',
            name='program_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='programphoto'),
        ),
    ]
