# Generated by Django 4.2.9 on 2025-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0050_alter_programoffice_program_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='dataapprove',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
