# Generated by Django 4.2.9 on 2025-02-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0051_computeraccessory_dataapprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='date_approve',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
