# Generated by Django 4.2.9 on 2025-03-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0052_computeraccessory_date_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('former_user', models.TextField(blank=True, max_length=50, null=True)),
                ('id_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.computeraccessory')),
            ],
        ),
    ]
