# Generated by Django 4.2.9 on 2025-03-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0053_formeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='formeruser',
            name='date_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
