# Generated by Django 4.2.9 on 2025-03-06 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0054_formeruser_date_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeraccessory',
            name='auditer',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computeraccessory',
            name='dataapprove',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='repairandpartchange',
            name='repairmethod',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
