# Generated by Django 4.2.9 on 2025-03-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0058_alter_repairandpartchange_hw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdevice',
            name='hw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow', to='cmsapp.computeraccessory'),
        ),
    ]
