# Generated by Django 4.2.9 on 2025-03-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0059_borrowdevice_hw_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowdevice',
            name='itemRecorder',
        ),
        migrations.RemoveField(
            model_name='borrowdevice',
            name='owner',
        ),
        migrations.AddField(
            model_name='borrowdevice',
            name='admin_allowborrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userallowborrow', to='cmsapp.profileuser'),
        ),
        migrations.AddField(
            model_name='borrowdevice',
            name='admin_returnback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreturn', to='cmsapp.profileuser'),
        ),
        migrations.AddField(
            model_name='borrowdevice',
            name='user_borrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userborrow', to='cmsapp.profileuser'),
        ),
        migrations.AlterField(
            model_name='computeraccessory',
            name='comstatus',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.repairstatus'),
        ),
    ]
