# Generated by Django 4.2.9 on 2025-04-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0069_alter_repairandpartchange_part_cat_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeraccessory',
            name='comstatus',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.repairstatus'),
        ),
    ]
