# Generated by Django 4.2.9 on 2025-06-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0071_profileuser_titlename_repairandpartchange_itsupport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='usergroup',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('superuser', 'superuser'), ('editer', 'editer'), ('reporter', 'reporter'), ('trainee', 'trainee')], max_length=100, null=True),
        ),
    ]
