# Generated by Django 4.2.9 on 2025-08-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0072_alter_profileuser_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomputeraccessory',
            name='hw_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hw_photos', to='cmsapp.computeraccessory'),
        ),
    ]
