# Generated by Django 4.2.9 on 2025-02-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_procument_id', models.TextField(blank=True, max_length=50, null=True)),
                ('server_service_name', models.TextField(blank=True, max_length=50, null=True)),
                ('server_brand_name', models.TextField(blank=True, max_length=50, null=True)),
                ('server_model_name', models.TextField(blank=True, max_length=50, null=True)),
                ('server_year_register', models.DateField(blank=True, null=True)),
                ('server_domain_name', models.TextField(blank=True, max_length=50, null=True)),
                ('server_ip', models.TextField(blank=True, max_length=50, null=True)),
                ('server_user', models.TextField(blank=True, max_length=50, null=True)),
                ('server_password', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
