# Generated by Django 4.2.9 on 2025-02-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0050_alter_programoffice_program_photo'),
        ('server_mainten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerVerMainten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('case_diag', models.CharField(max_length=100)),
                ('resolve_Methode', models.TextField(blank=True, max_length=1000, null=True)),
                ('server_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_mainten.server')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.profileuser')),
            ],
        ),
        migrations.CreateModel(
            name='ImageServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_case', models.ImageField(blank=True, null=True, upload_to='imgserverdiag')),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_mainten.servermainten')),
            ],
        ),
    ]
