# Generated by Django 4.2.9 on 2025-02-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_mainten', '0002_servermainten_imageserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageserver',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='imageserver',
            name='img_case',
        ),
        migrations.AddField(
            model_name='imageserver',
            name='img_server',
            field=models.ImageField(blank=True, null=True, upload_to='imgserver'),
        ),
        migrations.AddField(
            model_name='imageserver',
            name='server_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_mainten.server'),
        ),
        migrations.CreateModel(
            name='ImageServerRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_case', models.ImageField(blank=True, null=True, upload_to='imgserverdiag')),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_mainten.servermainten')),
            ],
        ),
    ]
