# Generated by Django 4.2.9 on 2025-02-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_mainten', '0003_remove_imageserver_case_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_domain_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_procument_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_service_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_year_register',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
