# Generated by Django 4.2.9 on 2025-02-17 09:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_mainten', '0004_alter_server_server_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermainten',
            name='resolve_Methode',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
