"""
Django settings for kbocms project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
#import pymysql  # ไว้สำหรับการแปลง database form sqlite3 to mysql
#pymysql.install_as_MySQLdb() # ไว้สำหรับการแปลง database form sqlite3 to mysql
from pathlib import Path
DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd6+u*s30w^@)m$&xx#ld5&p9v5ve^xenoosi^p@@-6amqagwvs'

'''
copy secert key to textfile to folder static project
SECRET_KEY = 'd6+u*s30w^@)m$&xx#ld5&p9v5ve^xenoosi^p@@-6amqagwvs'

with open(os.path.join(BASE_DIR,'secret_key.txt')) as f:
    SECRET_KEY = f.read().strip()
'''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
ALLOW_UNICODE_SLUGS  = True


# Application definition

INSTALLED_APPS = [

    'cmsapp',
    'cmsapp_backend',
    'vdoconf_conclusion',
    'server_mainten',
    'sparepart',

    #'qr_code'
    'hitcount',
    'captcha',    
    'datetimewidget',
    'jazzmin',      
    'ckeditor',  
    'fontawesomefree',
    'djmoney',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]



ROOT_URLCONF = 'kbocms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [ 'cmsapp/template'], 
        'DIRS': [os.path.join(BASE_DIR,'cmsapp/template')],


        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kbocms.wsgi.application'


#Database # [เป็นการใช้งาน sqlite3 database]##############################3
#https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3', old
        'NAME': os.path.join(BASE_DIR,'db.sqlite3'),

    }
}

# [เป็นการใช้งาน mysql database]##################################
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # Or use 'mysql.connector.django'
#         'NAME': 'KBOCMS',
#         'USER': 'kbocms',
#         'PASSWORD': 'kbo2568@KboCms',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#         }
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator','OPTIONS':{'min_length':12}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {   
        'NAME': 'kbocms.validators.CustomCharacterPasswordValidator',
    },      # check pass word charector 
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
'''
STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR,"static")

STATICFILES_DIRS = [os.path.join(BASE_DIR,"static")] 

MEDIA_ROOT = os.path.join(BASE_DIR,"media/")

MEDIA_URL = 'media/'

'''
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'itadmin_page'
LOGOUT_REDIRECT_URL = '/login/'

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

if DEBUG:

  STATICFILES_DIRS = [os.path.join(BASE_DIR, 'kbocms','static')]

else:

  STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


'''
STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # แหล่ง static ไฟล์ตอนพัฒนา

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')    # ปลายทางของ collectstatic

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
'''


'''

#it for develop no change anything 

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

if DEBUG:

  STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

else:

  STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

'''



