# Generated by Django 4.2.9 on 2024-11-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_province', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trianee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainee_firstname', models.CharField(max_length=100)),
                ('Trainee_lastname', models.CharField(max_length=100)),
                ('Training_start', models.DateTimeField()),
                ('Training_finish', models.DateTimeField()),
                ('Training_phone', models.TextField(max_length=10)),
                ('phone_contact', models.TextField(max_length=10)),
                ('photograph', models.FileField(blank=True, null=True, upload_to='TrianeePhoto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Trainee_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp_backend.degree')),
                ('Trainee_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp_backend.school')),
            ],
        ),
    ]
