# Generated by Django 4.2.9 on 2024-11-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='trianee',
            name='title_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp_backend.titlename'),
        ),
    ]
