# Generated by Django 4.2.9 on 2024-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0002_titlename_trianee_title_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trianee',
            name='subject_ability',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trianee',
            name='Training_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trianee',
            name='phone_contact',
            field=models.CharField(max_length=10),
        ),
    ]
