# Generated by Django 4.2.9 on 2024-12-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0003_trianee_subject_ability_alter_trianee_training_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trianee',
            new_name='Trainee',
        ),
    ]
