# Generated by Django 4.2.9 on 2024-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0004_rename_trianee_trainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
