# Generated by Django 4.2.9 on 2024-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0005_trainee_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='phone_teacher',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trainee',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
