# Generated by Django 4.2.9 on 2024-12-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0006_trainee_phone_teacher_trainee_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='phone_contact',
        ),
    ]
