# Generated by Django 4.2.9 on 2025-01-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0007_remove_trainee_phone_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, default='user.jpg', null=True, upload_to='images-cloud')),
            ],
        ),
        migrations.AlterField(
            model_name='trainee',
            name='photograph',
            field=models.FileField(blank=True, default='user.jpg', null=True, upload_to='TrianeePhoto'),
        ),
    ]
