# Generated by Django 4.2.9 on 2025-02-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0008_imagescloud_alter_trainee_photograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagescloud',
            name='trainee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp_backend.trainee'),
        ),
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('workdisc', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.IntegerField()),
                ('result', models.BooleanField(default=False)),
                ('remark', models.CharField(max_length=100)),
                ('trainee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp_backend.trainee')),
            ],
        ),
    ]
