# Generated by Django 4.2.9 on 2025-02-05 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0009_imagescloud_trainee_id_dailyworkreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkreport',
            name='workdisc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
