# Generated by Django 4.2.9 on 2025-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0010_alter_dailyworkreport_workdisc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='workitem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkreport',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
