# Generated by Django 4.2.9 on 2025-02-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0011_dailyworkreport_workitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagescloud',
            name='trainee_id',
        ),
        migrations.DeleteModel(
            name='DailyWorkReport',
        ),
    ]
