# Generated by Django 4.2.9 on 2025-02-05 22:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0050_alter_programoffice_program_photo'),
        ('cmsapp_backend', '0012_remove_imagescloud_trainee_id_delete_dailyworkreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('workitem', models.CharField(blank=True, max_length=100, null=True)),
                ('workdisc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('result', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('usertrinee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.profileuser')),
            ],
        ),
        migrations.AddField(
            model_name='imagescloud',
            name='usertrainee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp_backend.dailyworkreport'),
        ),
    ]
