# Generated by Django 4.2.9 on 2025-02-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0013_dailyworkreport_imagescloud_usertrainee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagescloud',
            old_name='usertrainee_id',
            new_name='workid',
        ),
    ]
