# Generated by Django 4.2.9 on 2025-02-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0014_rename_usertrainee_id_imagescloud_workid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagescloud',
            name='Date',
        ),
        migrations.AlterField(
            model_name='imagescloud',
            name='images',
            field=models.ImageField(blank=True, default='defaultpicture.jpg', null=True, upload_to='images-cloud'),
        ),
    ]
