# Generated by Django 4.2.9 on 2025-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0017_remove_dailyworkreport_repair_and_part_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkreport',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
