# Generated by Django 4.2.9 on 2025-04-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0070_alter_computeraccessory_comstatus'),
        ('cmsapp_backend', '0018_alter_dailyworkreport_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='traineeUser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.profileuser'),
        ),
    ]
