# Generated by Django 4.2.9 on 2025-05-03 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp_backend', '0019_trainee_traineeuser_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyworkreport',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Work Report', 'verbose_name_plural': 'Daily Work Reports'},
        ),
        migrations.AlterField(
            model_name='dailyworkreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyworkreport',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
