# Generated by Django 4.2.9 on 2025-02-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmsapp', '0050_alter_programoffice_program_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VdoconfConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdoconfdate', models.DateTimeField(blank=True)),
                ('vdoconftitle', models.CharField(blank=True, max_length=50, null=True)),
                ('confDetail', models.TextField(blank=True, max_length=50, null=True)),
                ('link_url_vdo', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.profileuser')),
            ],
        ),
        migrations.CreateModel(
            name='VdoConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ImageField(blank=True, null=True, upload_to='vdoconf')),
                ('vdoconf_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vdoconf_conclusion.vdoconfconclusion')),
            ],
        ),
        migrations.CreateModel(
            name='ImageConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_vdoconf', models.ImageField(blank=True, null=True, upload_to='imgvdoconf')),
                ('vdoconf_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vdoconf_conclusion.vdoconfconclusion')),
            ],
        ),
    ]
