# Generated by Django 4.2.9 on 2025-02-17 09:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdoconf_conclusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdoconfconclusion',
            name='confDetail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
