# Generated by Django 4.2.9 on 2025-02-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmsapp', '0052_computeraccessory_date_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsRepairOrderParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_id', models.CharField(blank=True, max_length=10, null=True)),
                ('part_amount_use', models.IntegerField()),
                ('computer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.computeraccessory')),
            ],
        ),
        migrations.CreateModel(
            name='PartsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('parts_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.partsname')),
            ],
        ),
        migrations.CreateModel(
            name='PartRepairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='part_repair')),
                ('itemrepair_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.itemsrepairorderparts')),
            ],
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='parts_image')),
                ('partstock_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.partsname')),
            ],
        ),
        migrations.AddField(
            model_name='itemsrepairorderparts',
            name='part_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.partsname'),
        ),
        migrations.AddField(
            model_name='itemsrepairorderparts',
            name='user_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.profileuser'),
        ),
    ]
