# Generated by Django 4.2.9 on 2025-03-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0060_remove_borrowdevice_itemrecorder_and_more'),
        ('sparepart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsrepairorderparts',
            name='user_recorder',
        ),
        migrations.AddField(
            model_name='itemsrepairorderparts',
            name='admin_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_recorder', to='cmsapp.profileuser'),
        ),
        migrations.AddField(
            model_name='itemsrepairorderparts',
            name='part_sn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itemsrepairorderparts',
            name='user_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_oder', to='cmsapp.profileuser'),
        ),
    ]
