# Generated by Django 4.2.9 on 2025-03-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0002_remove_itemsrepairorderparts_user_recorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsname',
            old_name='past_name',
            new_name='parts_name',
        ),
    ]
