# Generated by Django 4.2.9 on 2025-03-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0003_rename_past_name_partsname_parts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsstock',
            name='total',
        ),
        migrations.AddField(
            model_name='partsstock',
            name='spec_parts',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
