# Generated by Django 4.2.9 on 2025-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0004_remove_partsstock_total_partsstock_spec_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsstock',
            name='spec_parts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
