# Generated by Django 4.2.9 on 2025-03-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0061_alter_repairandpartchange_partchange'),
        ('sparepart', '0005_alter_partsstock_spec_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsrepairorderparts',
            name='computer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_id', to='cmsapp.repairandpartchange'),
        ),
        migrations.AlterField(
            model_name='itemsrepairorderparts',
            name='part_sn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
