# Generated by Django 4.2.9 on 2025-03-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0006_alter_itemsrepairorderparts_computer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsstock',
            old_name='spec_parts',
            new_name='parts_details',
        ),
        migrations.AddField(
            model_name='partsname',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partsstock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
