# Generated by Django 4.2.9 on 2025-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0007_rename_spec_parts_partsstock_parts_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsstock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
