# Generated by Django 4.2.9 on 2025-04-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0064_remove_repairandpartchange_partchange'),
        ('sparepart', '0008_alter_partsstock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartsSubCatName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_sub_name', models.TextField(blank=True, null=True)),
                ('parts_cat_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.parts_category')),
            ],
        ),
        migrations.RemoveField(
            model_name='partsstock',
            name='parts_name',
        ),
        migrations.AlterField(
            model_name='itemsrepairorderparts',
            name='part_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.partsstock'),
        ),
        migrations.AlterField(
            model_name='partimage',
            name='partstock_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.partsstock'),
        ),
        migrations.DeleteModel(
            name='PartsName',
        ),
        migrations.AddField(
            model_name='partsstock',
            name='parts_cat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.parts_category'),
        ),
        migrations.AddField(
            model_name='partsstock',
            name='parts_sub_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sparepart.partssubcatname'),
        ),
    ]
