# Generated by Django 4.2.9 on 2025-04-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0009_parts_category_partssubcatname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partssubcatname',
            name='parts_sub_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
